replicaCount: 1

image:
  registry: ghcr.io
  repository: aet-devops26/team-bnd
  pullPolicy: Always
  tag: "latest"

spring:
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  database:
    host: "alexandria-postgres-db"
    port: "5432"
    name: "alexandria"
    username: "postgres"
    password: "postgres-password"
  oidc:
    issuerUri: "https://alexandria.stud.k8s.aet.cit.tum.de/keycloak/realms/alexandria"
    jwkSetUri: "http://alexandria-keycloak:8080/keycloak/realms/alexandria/protocol/openid-connect/certs"
    userIdClaim: "sub"
    usernameClaim: "preferred_username"
    rolesClaim: "roles"

client:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 128Mi

genai:
  baseUrl: "http://alexandria-genai:8000"
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

ingress:
  enabled: true
  className: nginx
  host: alexandria.stud.k8s.aet.cit.tum.de

keycloak:
  keycloak:
    adminPassword: "admin"
    proxyHeaders: "xforwarded"
    hostname: "https://alexandria.stud.k8s.aet.cit.tum.de/keycloak"
    httpRelativePath: /keycloak
    extraArgs:
      - "--hostname-backchannel-dynamic=true"
  realm:
    import: true
    existingSecret: alexandria-oidc-realm
  extraEnvVars:
    - name: KEYCLOAK_REDIRECT_URI
      value: "https://alexandria.stud.k8s.aet.cit.tum.de/*"
    - name: KEYCLOAK_WEB_ORIGIN
      value: "https://alexandria.stud.k8s.aet.cit.tum.de"
  database:
    type: postgres
    host: "alexandria-postgres-db"
    port: "5432"
    name: "keycloak"
    username: "postgres"
    password: "postgres-password"
  postgres:
    enabled: false
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1024Mi
  initContainers:
    copyQuarkusLib:
      resources:
        requests:
          cpu: 20m
          memory: 32Mi
        limits:
          cpu: 40m
          memory: 64Mi
  extraInitContainers:
    - name: wait-for-postgres
      image: postgres:16-alpine
      command:
        - sh
        - -c
        - |
          until pg_isready -h alexandria-postgres-db -p 5432 -U postgres; do
            echo "waiting for database..."
            sleep 2
          done
          echo "database is ready"
      resources:
        requests:
          cpu: 20m
          memory: 32Mi
        limits:
          cpu: 40m
          memory: 64Mi

postgres-db:
  auth:
    username: "postgres"
    password: "postgres-password"
    database: "keycloak"
  initdb:
    scripts:
      create-alexandria-db.sql: |
        CREATE DATABASE alexandria;
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1000m"
