services:
  client:
    build:
      context: services/client/
      dockerfile: Dockerfile
    ports:
      - 8082:80
  spring:
    build: services/spring/
    ports:
      - 8080:8080
  genai:
    build: services/genai/
    ports:
      - 8000:8000
    environment:
      - GENAI_LOG_LEVEL=info
