apiVersion: v1
kind: Service
metadata:
  name: {{ include "alexandria.fullname" . }}-genai
  labels:
    {{- include "alexandria.labels" . | nindent 4 }}
    app: genai
    app.kubernetes.io/component: ai-service
spec:
  type: ClusterIP
  selector:
    {{- include "alexandria.selectorLabels" . | nindent 4 }}
    app: genai
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
