{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "alexandria.fullname" . }}-grafana
  namespace: {{ include "alexandria.monitoringNamespace" . }}
  labels:
    {{- include "alexandria.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.grafana.persistence.size }}
{{- end }}
