{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "alexandria.fullname" . }}-grafana-provisioning
  namespace: {{ include "alexandria.monitoringNamespace" . }}
  labels:
    {{- include "alexandria.labels" . | nindent 4 }}
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        uid: prometheus
        type: prometheus
        access: proxy
        url: http://{{ include "alexandria.fullname" . }}-prometheus:9090/prometheus
        isDefault: true
        editable: false
  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: Alexandria
        orgId: 1
        folder: Alexandria
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards
          foldersFromFilesStructure: false
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "alexandria.fullname" . }}-grafana-dashboards
  namespace: {{ include "alexandria.monitoringNamespace" . }}
  labels:
    {{- include "alexandria.labels" . | nindent 4 }}
data:
{{- range $path, $_ := .Files.Glob "files/dashboards/*.json" }}
  {{ base $path }}: |-
{{ $.Files.Get $path | indent 4 }}
{{- end }}
{{- end }}
