{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "alexandria.fullname" . }}-grafana
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "alexandria.labels" . | nindent 4 }}
    app: grafana
    app.kubernetes.io/component: monitoring
spec:
  type: ClusterIP
  selector:
    {{- include "alexandria.selectorLabels" . | nindent 4 }}
    app: grafana
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
{{- end }}
