{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "alexandria.fullname" . }}
  labels:
    {{- include "alexandria.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "alexandria.fullname" . }}-client
                port:
                  number: 80
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "alexandria.fullname" . }}-spring
                port:
                  number: 8080
          - path: /genai
            pathType: Prefix
            backend:
              service:
                name: {{ include "alexandria.fullname" . }}-genai
                port:
                  number: 8000
          - path: /keycloak
            pathType: Prefix
            backend:
              service:
                name: {{ include "alexandria.fullname" . }}-keycloak
                port:
                  number: 8080
{{- end }}
