{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "alexandria.fullname" . }}
  annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
  labels:
    {{- include "alexandria.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  tls:
    - hosts:
      - {{ .Values.ingress.host }}
      secretName: "alexandria-tls"
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "alexandria.fullname" . }}-client
                port:
                  number: 80
          - path: /api/v1/users
            pathType: Prefix
            backend:
              service:
                name: {{ include "alexandria.fullname" . }}-user-service
                port:
                  number: 8080
          - path: /user-service/docs
            pathType: Prefix
            backend:
              service:
                name: {{ include "alexandria.fullname" . }}-user-service
                port:
                  number: 8080
          - path: /user-service/swagger-ui
            pathType: Prefix
            backend:
              service:
                name: {{ include "alexandria.fullname" . }}-user-service
                port:
                  number: 8080
          - path: /user-service/v3/api-docs
            pathType: Prefix
            backend:
              service:
                name: {{ include "alexandria.fullname" . }}-user-service
                port:
                  number: 8080
          - path: /api/v1/knowledgebase
            pathType: Prefix
            backend:
              service:
                name: {{ include "alexandria.fullname" . }}-knowledgebase-service
                port:
                  number: 8080
          - path: /knowledgebase-service/docs
            pathType: Prefix
            backend:
              service:
                name: {{ include "alexandria.fullname" . }}-knowledgebase-service
                port:
                  number: 8080
          - path: /knowledgebase-service/swagger-ui
            pathType: Prefix
            backend:
              service:
                name: {{ include "alexandria.fullname" . }}-knowledgebase-service
                port:
                  number: 8080
          - path: /knowledgebase-service/v3/api-docs
            pathType: Prefix
            backend:
              service:
                name: {{ include "alexandria.fullname" . }}-knowledgebase-service
                port:
                  number: 8080
          - path: /api/v1/qa
            pathType: Prefix
            backend:
              service:
                name: {{ include "alexandria.fullname" . }}-qa-service
                port:
                  number: 8080
          - path: /qa-service/docs
            pathType: Prefix
            backend:
              service:
                name: {{ include "alexandria.fullname" . }}-qa-service
                port:
                  number: 8080
          - path: /qa-service/swagger-ui
            pathType: Prefix
            backend:
              service:
                name: {{ include "alexandria.fullname" . }}-qa-service
                port:
                  number: 8080
          - path: /qa-service/v3/api-docs
            pathType: Prefix
            backend:
              service:
                name: {{ include "alexandria.fullname" . }}-qa-service
                port:
                  number: 8080
          - path: /genai/docs
            pathType: Prefix
            backend:
              service:
                name: {{ include "alexandria.fullname" . }}-genai
                port:
                  number: 8000
          - path: /genai/redoc
            pathType: Prefix
            backend:
              service:
                name: {{ include "alexandria.fullname" . }}-genai
                port:
                  number: 8000
          - path: /genai/openapi.json
            pathType: Prefix
            backend:
              service:
                name: {{ include "alexandria.fullname" . }}-genai
                port:
                  number: 8000
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: {{ include "alexandria.fullname" . }}-keycloak
                port:
                  number: 8080
{{- end }}
