apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-keycloak-theme
  labels:
    {{- include "alexandria.labels" . | nindent 4 }}
    app: keycloak
data:
  theme.properties: |
    {{- .Files.Get "files/keycloak-theme/login/theme.properties" | nindent 4 }}
  styles.css: |
    {{- .Files.Get "files/keycloak-theme/login/resources/css/styles.css" | nindent 4 }}
