{{- if and .Values.monitoring.createNamespace (or .Values.prometheus.enabled .Values.grafana.enabled) }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "alexandria.monitoringNamespace" . }}
  labels:
    {{- include "alexandria.labels" . | nindent 4 }}
    app.kubernetes.io/component: monitoring
{{- end }}
