apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alexandria.fullname" . }}-oidc-realm
  labels:
    {{- include "alexandria.labels" . | nindent 4 }}
    app: keycloak
type: Opaque
stringData:
  realm.json: |
    {{- .Files.Get "files/oidc/realm.json" | nindent 4 }}
