{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "alexandria.fullname" . }}-prometheus
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "alexandria.labels" . | nindent 4 }}
    app: prometheus
    app.kubernetes.io/component: monitoring
spec:
  type: ClusterIP
  selector:
    {{- include "alexandria.selectorLabels" . | nindent 4 }}
    app: prometheus
  ports:
    - name: http
      port: 9090
      targetPort: http
      protocol: TCP
{{- end }}
