apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alexandria.fullname" . }}-spring-secrets
  labels:
    {{- include "alexandria.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-password: {{ .Values.spring.database.password | quote }}
  s3-access-key: {{ .Values.s3.accessKey | quote }}
  s3-secret-key: {{ .Values.s3.secretKey | quote }}
