apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alexandria.fullname" . }}-spring-secrets
  labels:
    {{- include "alexandria.labels" . | nindent 4 }}
    app: spring
type: Opaque
stringData:
  postgres-password: {{ .Values.spring.database.password | quote }}
