apiVersion: v1
kind: Service
metadata:
  name: {{ include "alexandria.fullname" . }}-spring
  labels:
    {{- include "alexandria.labels" . | nindent 4 }}
    app: spring
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    {{- include "alexandria.selectorLabels" . | nindent 4 }}
    app: spring
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
