apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "alexandria.fullname" . }}-weaviate
  labels:
    {{- include "alexandria.labels" . | nindent 4 }}
    app: weaviate
    app.kubernetes.io/component: vector-database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.weaviate.persistence.size | default "2Gi" }}
