plugins {
	id 'org.springdoc.openapi-gradle-plugin'
}

openApi {
	apiDocsUrl = "http://localhost:8080/qa-service/v3/api-docs.yaml"
	outputDir = file("$projectDir/../../../api")
	outputFileName = "spring-qa-openapi.yaml"
	customBootRun {
		args = ["--spring.profiles.active=openapi"]
	}
}

dependencies {
	implementation project(':common')
}
