#!/usr/bin/env bash

set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "${script_dir}/../.." && pwd)"

env_output_path="${ENV_OUTPUT_PATH:-${script_dir}/.env}"
env_example_path="${ENV_EXAMPLE_PATH:-${repo_root}/.env.example}"
secret_placeholder="secret-with-64-bit-entropy-eg-16-hex-chars"
deploy_mode="${DEPLOY_MODE:-}"
public_base_url="${PUBLIC_BASE_URL:-}"
public_domain="${PUBLIC_DOMAIN:-}"
acme_email="${ACME_EMAIL:-}"
llm_api_key="${LLM_API_KEY:-}"
default_base_url="${DEFAULT_BASE_URL:-http://localhost}"
assume_yes="${ASSUME_YES:-false}"

interactive() { [[ -t 0 && -t 2 && "${assume_yes}" != "true" ]]; }

ask() {
	local __var="$1" __msg="$2" __default="${3:-}" __reply=""
	if ! interactive; then
		printf -v "${__var}" '%s' "${__default}"
		return 0
	fi
	if [[ -n "${__default}" ]]; then
		read -r -p "${__msg} [${__default}]: " __reply || true
		[[ -z "${__reply}" ]] && __reply="${__default}"
	else
		read -r -p "${__msg}: " __reply || true
	fi
	printf -v "${__var}" '%s' "${__reply}"
}

# tr gets SIGPIPE once head has read enough; drop pipefail in the subshell so that
# expected failure does not abort the script.
gen_secret() {
	(
		set +o pipefail
		LC_ALL=C tr -dc 'A-Za-z0-9' < /dev/urandom | head -c "${1:-32}"
	)
}

# Default to keeping an existing file so re-runs never rotate live secrets. Only a
# confirmed prompt or OVERWRITE_ENV=true regenerates it.
if [[ -f "${env_output_path}" ]]; then
	overwrite="no"
	if [[ "${OVERWRITE_ENV:-}" == "true" ]]; then
		overwrite="yes"
	elif interactive; then
		read -r -p "${env_output_path} exists. Overwrite and regenerate secrets? [y/N]: " reply || true
		[[ "${reply}" =~ ^(y|Y|yes|YES)$ ]] && overwrite="yes"
	fi
	if [[ "${overwrite}" != "yes" ]]; then
		echo "Keeping existing ${env_output_path}."
		exit 0
	fi
fi

if [[ -z "${deploy_mode}" ]]; then
	if [[ -n "${public_domain}" ]]; then
		deploy_mode="https"
	elif interactive; then
		echo "Deployment mode:" >&2
		echo "  1) http  - plain HTTP on localhost or a public IP" >&2
		echo "  2) https - Let's Encrypt TLS for a domain" >&2
		mode_choice=""
		ask mode_choice "Choose 1 or 2" "1"
		[[ "${mode_choice}" == "2" || "${mode_choice}" == "https" ]] && deploy_mode="https" || deploy_mode="http"
	else
		deploy_mode="http"
	fi
fi

if [[ "${deploy_mode}" == "https" ]]; then
	[[ -z "${public_domain}" ]] && ask public_domain "Public domain (e.g. alexandria.ddnss.de)" ""
	[[ -z "${public_domain}" ]] && {
		echo "A domain is required for https mode." >&2
		exit 1
	}
	public_base_url="${public_base_url:-https://${public_domain}}"
	[[ -z "${acme_email}" ]] && ask acme_email "ACME account email for Let's Encrypt" ""
	[[ -z "${acme_email}" ]] && {
		echo "An ACME email is required for https mode." >&2
		exit 1
	}
else
	[[ -z "${public_base_url}" ]] && ask public_base_url "Public base URL (scheme + host, no trailing slash)" "${default_base_url}"
fi

public_base_url="${public_base_url%/}"
[[ -z "${llm_api_key}" ]] && ask llm_api_key "LLM API key (blank to fill in later)" ""

# Which vars need a generated secret is driven by the shared placeholder in
# .env.example, so adding a secret var there is picked up here without touching this script.
if [[ ! -f "${env_example_path}" ]]; then
	echo "Cannot find ${env_example_path} to detect which secrets to generate." >&2
	exit 1
fi
mapfile -t secret_vars < <(grep -E "^# [A-Za-z_][A-Za-z0-9_]*=\"${secret_placeholder}\"" "${env_example_path}" | sed -E 's/^# ([A-Za-z_][A-Za-z0-9_]*)=.*/\1/')
if [[ ${#secret_vars[@]} -eq 0 ]]; then
	echo "No secret placeholders found in ${env_example_path}." >&2
	exit 1
fi

umask 077
{
	echo "# Generated by infra/azure/generate-env.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)."
	echo "# Holds deployment secrets. Do not commit; regenerate with generate-env.sh."
	echo ""
	echo "PUBLIC_BASE_URL=\"${public_base_url}\""
	if [[ "${deploy_mode}" == "https" ]]; then
		echo "PUBLIC_DOMAIN=\"${public_domain}\""
		echo "ACME_EMAIL=\"${acme_email}\""
	fi
	echo ""
	for secret_var in "${secret_vars[@]}"; do
		echo "${secret_var}=\"$(gen_secret 32)\""
	done
	if [[ -n "${llm_api_key}" ]]; then
		echo ""
		echo "LLM_API_KEY=\"${llm_api_key}\""
	fi
} > "${env_output_path}"
chmod 600 "${env_output_path}"

echo "Wrote ${env_output_path} (mode 600)."
[[ -z "${llm_api_key}" ]] && echo "Note: LLM_API_KEY is unset. GenAI needs it; add it before deploying." || true
